#!/usr/bin/env node
/**
 * build.mjs — compose `lib/client.js` (the browser bundle) from dict/pl/*.json.
 *
 * The generated bundle is committed, so a user installing the pack from GitHub
 * or npm never needs a build step. Run this after editing any dictionary:
 *
 *   node scripts/build.mjs
 *
 * The output is one self-contained bundle in the harness client-module loader
 * format (`window.__ModuleLoader__.load`), the same shape the official client
 * packages ship. The bundle registers the Polish language against
 * `ctx.locale.addLanguage` and every namespace's dictionary against
 * `ctx.locale.register`; the official registry owns fallback to English for
 * keys this pack does not cover yet.
 */

import { readdirSync, readFileSync, writeFileSync, mkdirSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..')
const DICT_DIR = join(ROOT, 'dict', 'pl')
const OUT_FILE = join(ROOT, 'lib', 'client.js')

/** Language definition published into the locale catalog. */
const LANGUAGE = { id: 'pl', label: 'Polski', fallback: 'en' }

/** Package id; must equal the package.json `name` the loader row mounts. */
const PACKAGE_ID = 'dsh-locale-pl'

let files
try {
  files = readdirSync(DICT_DIR).filter((f) => f.endsWith('.json')).sort()
} catch {
  console.error('build: dict/pl/ not found — nothing to build')
  process.exit(1)
}
if (files.length === 0) {
  console.error('build: dict/pl/ is empty — nothing to build')
  process.exit(1)
}

/** @type {Record<string, Record<string, string>>} */
const dictionaries = {}
for (const file of files) {
  const ns = file.replace(/\.json$/, '')
  const dict = JSON.parse(readFileSync(join(DICT_DIR, file), 'utf8'))
  const keys = Object.keys(dict)
  if (keys.length === 0) {
    console.error(`build: dict/pl/${file} has no keys`)
    process.exit(1)
  }
  for (const key of keys) {
    if (typeof dict[key] !== 'string' || dict[key].length === 0) {
      console.error(`build: dict/pl/${file} key '${key}' must be a non-empty string`)
      process.exit(1)
    }
  }
  dictionaries[ns] = dict
}

const banner = `// GENERATED by scripts/build.mjs — do not edit by hand.
// Edit dict/pl/*.json and run \`node scripts/build.mjs\` instead.
// Format: harness client-module loader bundle (window.__ModuleLoader__.load).
`

const body = `window.__ModuleLoader__.load({
	id: "${PACKAGE_ID}",
	factory: (require) => {
		var module = { exports: {} };
		var exports = module.exports;
		Object.defineProperty(exports, Symbol.toStringTag, { value: "Module" });

		const LANGUAGE = ${JSON.stringify(LANGUAGE)};

		const DICTIONARIES = ${JSON.stringify(dictionaries, null, 2)};

		const inject = ['locale'];

		function apply(ctx) {
			ctx.effect(
				() => ctx.locale.addLanguage(LANGUAGE),
				'${PACKAGE_ID}: language',
			)
			for (const [ns, dict] of Object.entries(DICTIONARIES)) {
				ctx.effect(
					() => ctx.locale.register(ns, '${LANGUAGE.id}', dict),
					\`${PACKAGE_ID}: \${ns} dictionary\`,
				)
			}
		}

		exports.name = '${PACKAGE_ID}';
		exports.apply = apply;
		exports.inject = inject;
		return module.exports;
	},
});
`

mkdirSync(dirname(OUT_FILE), { recursive: true })
writeFileSync(OUT_FILE, banner + body)
const namespaces = Object.keys(dictionaries).length
const keys = Object.values(dictionaries).reduce((sum, d) => sum + Object.keys(d).length, 0)
console.log(`build: wrote ${OUT_FILE} (${namespaces} namespaces, ${keys} keys)`)
